extern const GeoLayout sonk_Left_Hand_Open[];
extern const GeoLayout sonk_Right_Hand_Open[];
extern const GeoLayout sonk_Right_Hand_Peace[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sonk_Left_Hand_Open[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sonk_Right_Hand_Open[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sonk_Right_Hand_Peace[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt1[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt2[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt3[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt4[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt5[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt6[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt7[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt1[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_sonk_Left_Hand_Open[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_sonk_Right_Hand_Open[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_sonk_Right_Hand_Peace[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt2[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_sonk_Left_Hand_Open[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_sonk_Right_Hand_Open[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_sonk_Right_Hand_Peace[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt3[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt1[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt2[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt3[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt4[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt5[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt6[];
extern const GeoLayout sonk_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt7[];
extern const GeoLayout sonk_geo[];
extern Lights1 sonk_Gloves__GLOVES__lights;
extern Lights1 sonk_PANTS_lights;
extern Lights1 sonk_Metal__METAL__lights;
extern Lights1 sonk_SHIRT_lights;
extern Lights1 sonk_HAIR_lights;
extern Lights1 sonk_SKIN_lights;
extern Lights1 sonk_Open_Eyes__SKIN__lights;
extern Lights1 sonk_Nose__SKIN__lights;
extern Lights1 sonk_Half_Eyes__SKIN__lights;
extern Lights1 sonk_Closed_Eyes__SKIN__lights;
extern Lights1 sonk_Left_Eyes__SKIN__lights;
extern Lights1 sonk_Right_Eyes__SKIN__lights;
extern Lights1 sonk_Up_Eyes__SKIN__lights;
extern Lights1 sonk_Down_Eyes__SKIN__lights;
extern Lights1 sonk_Dead_Eyes__SKIN__lights;
extern Lights1 sonk_GLOVES_OUT_lights;
extern u8 sonk_custom_mario_metal_base_rgba16[];
extern u8 sonk_custom_mario_metal_shine_rgba16[];
extern u8 sonk_eyes_open_rgba16[];
extern u8 sonk_nose_rgba16[];
extern u8 sonk_eyes_half_rgba16[];
extern u8 sonk_eyes_closed_rgba16[];
extern u8 sonk_eyes_left_rgba16[];
extern u8 sonk_eyes_right_rgba16[];
extern u8 sonk_eyes_up_rgba16[];
extern u8 sonk_eyes_down_rgba16[];
extern u8 sonk_eyes_dead_rgba16[];
extern u8 sonk_wing_2_rgba16[];
extern u8 sonk_wing1_rgba16[];
extern Vtx sonk_Butt_mesh_layer_1_vtx_0[30];
extern Gfx sonk_Butt_mesh_layer_1_tri_0[];
extern Vtx sonk_Butt_mesh_layer_1_vtx_1[21];
extern Gfx sonk_Butt_mesh_layer_1_tri_1[];
extern Vtx sonk_Torso_mesh_layer_1_vtx_0[113];
extern Gfx sonk_Torso_mesh_layer_1_tri_0[];
extern Vtx sonk_Torso_mesh_layer_1_vtx_1[30];
extern Gfx sonk_Torso_mesh_layer_1_tri_1[];
extern Vtx sonk_Head_DL_mesh_layer_1_vtx_0[149];
extern Gfx sonk_Head_DL_mesh_layer_1_tri_0[];
extern Vtx sonk_Head_DL_mesh_layer_1_vtx_1[40];
extern Gfx sonk_Head_DL_mesh_layer_1_tri_1[];
extern Vtx sonk_Head_DL_mesh_layer_1_vtx_2[23];
extern Gfx sonk_Head_DL_mesh_layer_1_tri_2[];
extern Vtx sonk_Head_DL_mesh_layer_1_vtx_3[4];
extern Gfx sonk_Head_DL_mesh_layer_1_tri_3[];
extern Vtx sonk_Left_Wing_DL_mesh_layer_4_vtx_0[4];
extern Gfx sonk_Left_Wing_DL_mesh_layer_4_tri_0[];
extern Vtx sonk_Left_Wing_DL_mesh_layer_4_vtx_1[4];
extern Gfx sonk_Left_Wing_DL_mesh_layer_4_tri_1[];
extern Vtx sonk_Right_Wing_DL_mesh_layer_4_vtx_0[4];
extern Gfx sonk_Right_Wing_DL_mesh_layer_4_tri_0[];
extern Vtx sonk_Right_Wing_DL_mesh_layer_4_vtx_1[4];
extern Gfx sonk_Right_Wing_DL_mesh_layer_4_tri_1[];
extern Vtx sonk_Left_Arm_Color_mesh_layer_1_vtx_0[20];
extern Gfx sonk_Left_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx sonk_Left_Forearm_mesh_layer_1_vtx_0[16];
extern Gfx sonk_Left_Forearm_mesh_layer_1_tri_0[];
extern Vtx sonk_Left_Hand_DL_mesh_layer_1_vtx_0[11];
extern Gfx sonk_Left_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx sonk_Left_Hand_DL_mesh_layer_1_vtx_1[19];
extern Gfx sonk_Left_Hand_DL_mesh_layer_1_tri_1[];
extern Vtx sonk_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_vtx_0[24];
extern Gfx sonk_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_tri_0[];
extern Vtx sonk_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_vtx_1[15];
extern Gfx sonk_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_tri_1[];
extern Vtx sonk_Right_Arm_Color_mesh_layer_1_vtx_0[20];
extern Gfx sonk_Right_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx sonk_Right_Forearm_mesh_layer_1_vtx_0[16];
extern Gfx sonk_Right_Forearm_mesh_layer_1_tri_0[];
extern Vtx sonk_Right_Hand_DL_mesh_layer_1_vtx_0[19];
extern Gfx sonk_Right_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx sonk_Right_Hand_DL_mesh_layer_1_vtx_1[11];
extern Gfx sonk_Right_Hand_DL_mesh_layer_1_tri_1[];
extern Vtx sonk_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_vtx_0[24];
extern Gfx sonk_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_tri_0[];
extern Vtx sonk_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_vtx_1[15];
extern Gfx sonk_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_tri_1[];
extern Vtx sonk_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_vtx_0[15];
extern Gfx sonk_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_tri_0[];
extern Vtx sonk_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_vtx_1[29];
extern Gfx sonk_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_tri_1[];
extern Vtx sonk_Left_Thigh_Color_mesh_layer_1_vtx_0[17];
extern Gfx sonk_Left_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx sonk_Left_Leg_mesh_layer_1_vtx_0[12];
extern Gfx sonk_Left_Leg_mesh_layer_1_tri_0[];
extern Vtx sonk_Left_Shoe_mesh_layer_1_vtx_0[41];
extern Gfx sonk_Left_Shoe_mesh_layer_1_tri_0[];
extern Vtx sonk_Right_Thigh_Color_mesh_layer_1_vtx_0[17];
extern Gfx sonk_Right_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx sonk_Right_Leg_mesh_layer_1_vtx_0[12];
extern Gfx sonk_Right_Leg_mesh_layer_1_tri_0[];
extern Vtx sonk_Right_Shoe_DL_mesh_layer_1_vtx_0[39];
extern Gfx sonk_Right_Shoe_DL_mesh_layer_1_tri_0[];
extern Gfx mat_sonk_Gloves__GLOVES_[];
extern Gfx mat_revert_sonk_Gloves__GLOVES_[];
extern Gfx mat_sonk_PANTS[];
extern Gfx mat_revert_sonk_PANTS[];
extern Gfx mat_sonk_Metal__METAL_[];
extern Gfx mat_revert_sonk_Metal__METAL_[];
extern Gfx mat_sonk_SHIRT[];
extern Gfx mat_revert_sonk_SHIRT[];
extern Gfx mat_sonk_HAIR[];
extern Gfx mat_revert_sonk_HAIR[];
extern Gfx mat_sonk_SKIN[];
extern Gfx mat_revert_sonk_SKIN[];
extern Gfx mat_sonk_Open_Eyes__SKIN_[];
extern Gfx mat_revert_sonk_Open_Eyes__SKIN_[];
extern Gfx mat_sonk_Nose__SKIN_[];
extern Gfx mat_revert_sonk_Nose__SKIN_[];
extern Gfx mat_sonk_Half_Eyes__SKIN_[];
extern Gfx mat_revert_sonk_Half_Eyes__SKIN_[];
extern Gfx mat_sonk_Closed_Eyes__SKIN_[];
extern Gfx mat_revert_sonk_Closed_Eyes__SKIN_[];
extern Gfx mat_sonk_Left_Eyes__SKIN_[];
extern Gfx mat_revert_sonk_Left_Eyes__SKIN_[];
extern Gfx mat_sonk_Right_Eyes__SKIN_[];
extern Gfx mat_revert_sonk_Right_Eyes__SKIN_[];
extern Gfx mat_sonk_Up_Eyes__SKIN_[];
extern Gfx mat_revert_sonk_Up_Eyes__SKIN_[];
extern Gfx mat_sonk_Down_Eyes__SKIN_[];
extern Gfx mat_revert_sonk_Down_Eyes__SKIN_[];
extern Gfx mat_sonk_Dead_Eyes__SKIN_[];
extern Gfx mat_revert_sonk_Dead_Eyes__SKIN_[];
extern Gfx mat_sonk_Wing_Tip[];
extern Gfx mat_revert_sonk_Wing_Tip[];
extern Gfx mat_sonk_Wing_Base[];
extern Gfx mat_revert_sonk_Wing_Base[];
extern Gfx mat_sonk_GLOVES_OUT[];
extern Gfx mat_revert_sonk_GLOVES_OUT[];
extern Gfx sonk_Butt_mesh_layer_1[];
extern Gfx sonk_Butt_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx sonk_Torso_mesh_layer_1[];
extern Gfx sonk_Torso_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx sonk_Head_DL_mesh_layer_1[];
extern Gfx sonk_Head_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx sonk_Head_DL_mesh_layer_1_mat_override_Half_Eyes__SKIN__1[];
extern Gfx sonk_Head_DL_mesh_layer_1_mat_override_Closed_Eyes__SKIN__2[];
extern Gfx sonk_Head_DL_mesh_layer_1_mat_override_Left_Eyes__SKIN__3[];
extern Gfx sonk_Head_DL_mesh_layer_1_mat_override_Right_Eyes__SKIN__4[];
extern Gfx sonk_Head_DL_mesh_layer_1_mat_override_Up_Eyes__SKIN__5[];
extern Gfx sonk_Head_DL_mesh_layer_1_mat_override_Down_Eyes__SKIN__6[];
extern Gfx sonk_Head_DL_mesh_layer_1_mat_override_Dead_Eyes__SKIN__7[];
extern Gfx sonk_Left_Wing_DL_mesh_layer_4[];
extern Gfx sonk_Left_Wing_DL_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx sonk_Right_Wing_DL_mesh_layer_4[];
extern Gfx sonk_Right_Wing_DL_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx sonk_Left_Arm_Color_mesh_layer_1[];
extern Gfx sonk_Left_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx sonk_Left_Forearm_mesh_layer_1[];
extern Gfx sonk_Left_Forearm_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx sonk_Left_Hand_DL_mesh_layer_1[];
extern Gfx sonk_Left_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx sonk_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1[];
extern Gfx sonk_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx sonk_Right_Arm_Color_mesh_layer_1[];
extern Gfx sonk_Right_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx sonk_Right_Forearm_mesh_layer_1[];
extern Gfx sonk_Right_Forearm_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx sonk_Right_Hand_DL_mesh_layer_1[];
extern Gfx sonk_Right_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx sonk_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1[];
extern Gfx sonk_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx sonk_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1[];
extern Gfx sonk_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx sonk_Left_Thigh_Color_mesh_layer_1[];
extern Gfx sonk_Left_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx sonk_Left_Leg_mesh_layer_1[];
extern Gfx sonk_Left_Leg_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx sonk_Left_Shoe_mesh_layer_1[];
extern Gfx sonk_Left_Shoe_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx sonk_Right_Thigh_Color_mesh_layer_1[];
extern Gfx sonk_Right_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx sonk_Right_Leg_mesh_layer_1[];
extern Gfx sonk_Right_Leg_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx sonk_Right_Shoe_DL_mesh_layer_1[];
extern Gfx sonk_Right_Shoe_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
